name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'src/*'

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show trigger
        run: echo "Triggered by ${{ github.event_name }}"

      - name: Show environment
        run: |
          echo "Hello from GitHub Actions"
          uname -a
          pwd

      - name: List files
        run: ls -la

      - name: Show src/index.html
        run: cat src/index.html
